default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: <%= Figaro.env.pass_mysql %>
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: graduation-thesis_development

test:
  <<: *default
  database: graduation-thesis_test

production:
  <<: *default
  database: <%= Figaro.env.database %>
  username: <%= Figaro.env.username %>
  password: <%= Figaro.env.pass_mysql %>
